# syntax=docker/dockerfile:1
FROM azul/zulu-openjdk-alpine:17.0.2 AS build_image
ENV APP_HOME=/app
WORKDIR $APP_HOME
COPY build.gradle.kts settings.gradle.kts gradlew $APP_HOME
COPY gradle $APP_HOME/gradle
RUN ./gradlew build || return 0
COPY . .
RUN ./gradlew build

FROM azul/zulu-openjdk-alpine:17.0.2 as base
ENV ARTIFACT_NAME=notes.jar
ENV APP_HOME=/app
WORKDIR $APP_HOME
COPY --from=build_image $APP_HOME/build/libs/*.jar $ARTIFACT_NAME
EXPOSE 8080
CMD ["java", "-Dspring.profiles.active=mysql", "-jar", "notes.jar"]

